---
- name: Print machine OS family
  ansible.builtin.debug:
    var: ansible_facts

- name: Install Java
  ansible.builtin.apt:
    name: openjdk-17-jdk-headless
    update_cache: yes
  become: true

- name: Prevent Java from being upgraded
  ansible.builtin.dpkg_selections:
    name: java-common
    selection: hold
  become: true

- name: Install Docker prerequisites
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes
  become: true

- name: Create /etc/apt/keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
  become: true

- name: Get Docker repository key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    owner: root
  become: true

- name: Create and add a line to a file /etc/apt/sources.list.d/docker.list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: deb [arch={{ architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ os_code_name }} stable
    create: yes
    owner: root
  become: true

- name: Update cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install Docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes
  become: true

- name: Add jenkins user
  ansible.builtin.user:
    name: jenkins
    shell: /bin/bash
    groups: docker
    append: yes
  become: true